### ISSUE TITLE
"No space left on device" is a VERY common error. We should parse the logs / see if it contains that and notify the user.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#215]
### Is your enhancement related to a problem? Please describe

I get this error sometimes when building:

```
time="2024-03-21T11:51:03Z" level=fatal msg="writing blob: storing blob to file \"/var/tmp/container_images_storage3568874487/41\": write /var/tmp/container_images_storage3568874487/41: no space left on device"
Error: mkdir /etc/containers/networks: read-only file system
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.container-deploy", line 50, in main
    subprocess.run(
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['skopeo', 'copy', 'containers-storage:[overlay@/run/osbuild/containers/storage+/run/containers/storage]cf1e236535f087f89c3de5797ea6a867fe67377e5eda0cb902872b1d94f756b1', 'containers-storage:tmp-container-deploy-08387570473357']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.container-deploy", line 64, in <module>
    r = main(args["inputs"], args["tree"], args["options"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/osbuild/bin/org.osbuild.container-deploy", line 47, in main
    with contextlib.ExitStack() as cm:
  File "/usr/lib64/python3.12/contextlib.py", line 598, in __exit__
    raise exc_details[1]
  File "/usr/lib64/python3.12/contextlib.py", line 583, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/contextlib.py", line 466, in _exit_wrapper
    callback(*args, **kwds)
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'rmi', 'tmp-container-deploy-08387570473357']' returned non-zero exit status 125.

⏱  Duration: 7s
manifest - failed
Failed
Error: running osbuild failed: exit status 1
2024/03/21 11:51:04 error: running osbuild failed: exit status 1
```

As my system quickly fills up with builds.

### Describe the solution you'd like

We should parse and check to see if `no space left on device` was in the log output and notify the use that they are low on space.

**Comment by deboer-tim** [comment]
In the future a size column on not-dashboard would also help.

**Comment by cdrage** [comment]
Related to #221 , this error is encountered if the machine does not have enough RAM.

**Comment by deboer-tim** [comment]
Confirmed this is the same issue as #221.
