### ISSUE TITLE
Playwright e2e tests have broken dependency due to dependabot updates

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-extension-bootc#712]
### Bug description

Ref actions fail run: https://github.com/containers/podman-desktop-extension-bootc/actions/runs/10269395422/job/28414736482?pr=710

### Operating system

Everywhere

### Version

next (development version)

### Relevant log output

```shell
Run yarn add -D @podman-desktop/tests-playwright@next
yarn add v1.22.22
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "string-width@^5.1.2". Ignoring it.
warning Lockfile has incorrect entry for "wrap-ansi@^8.1.0". Ignoring it.
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "workspace-aggregator-87e5ce8b-f396-44f7-a576-3a905fab220e > autoprefixer@10.4.20" has unmet peer dependency "postcss@^8.1.0".
warning "workspace-aggregator-87e5ce8b-f396-44f7-a576-3a905fab220e > eslint-plugin-redundant-undefined@1.0.0" has incorrect peer dependency "@typescript-eslint/parser@^6.2.0".
warning "workspace-aggregator-87e5ce8b-f396-44f7-a576-3a905fab220e > frontend > @podman-desktop/ui-svelte@1.12.0-202408061335-cb7a329" has incorrect peer dependency "svelte@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-87e5ce8b-f396-44f7-a576-3a905fab220e > frontend > svelte-fa@4.0.2" has incorrect peer dependency "svelte@^4.0.0".
warning "workspace-aggregator-87e5ce8b-f396-44f7-a576-3a905fab220e > frontend > svelte-markdown@0.4.1" has incorrect peer dependency "svelte@^4.0.0".
warning "workspace-aggregator-87e5ce8b-f396-44f7-a576-3a905fab220e > frontend > @sveltejs/vite-plugin-svelte > svelte-hmr@0.16.0" has incorrect peer dependency "svelte@^3.19.0 || ^4.0.0".
warning " > @podman-desktop/tests-playwright@1.12.0-202408061335-cb7a329" has unmet peer dependency "@playwright/test@1.42.1".
warning " > @podman-desktop/tests-playwright@1.12.0-202408061335-cb7a329" has unmet peer dependency "electron@29.1.4".
error Invariant Violation: expected workspace package to exist for "@typescript-eslint/utils"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    at invariant (/usr/local/lib/node_modules/yarn/lib/cli.js:2318:15)
    at _loop2 (/usr/local/lib/node_modules/yarn/lib/cli.js:91560:9)
    at PackageHoister.init (/usr/local/lib/node_modules/yarn/lib/cli.js:91619:19)
    at PackageLinker.getFlatHoistedTree (/usr/local/lib/node_modules/yarn/lib/cli.js:48551:20)
    at PackageLinker.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:48562:27)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/usr/local/lib/node_modules/yarn/lib/cli.js:5539:28)
Error: Process completed with exit code 1
```

**Comment by deboer-tim** [comment]
I believe this was caused by #699, which bumped the eslint-plugin.

**Comment by odockal** [comment]
@deboer-tim that is correct. But I still do not understand why.

**Comment by odockal** [comment]
@benoitf suggested the problem is at yarn (1.2.2)[https://stackoverflow.com/questions/64060218/why-does-yarn-throw-invariant-violation-expected-workspace-package-to-exist-w]. We could probably add particular version (the latest/next) manually into package.json and then download deps. Simply do not use `yarn add` is a workaround.
