### ISSUE TITLE
KNOWN ISSUE: Unable to cross-arch build 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#808]
### Bug description

If you have output issues such as:

```
error: Performing deployment: Creating importer: Function not implemented (os error 38)
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 72, in <module>
    r = main(stage_args["tree"],
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 67, in main
    ostree_container_deploy(tree, inputs, osname, target_imgref, kopts)
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 41, in ostree_container_deploy
    ostree.cli("container", "image", "deploy",
  File "/run/osbuild/lib/osbuild/util/ostree.py", line 205, in cli
    return subprocess.run(["ostree"] + args,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,

manifest - failed 
```

There are current issues upstream regarding building the default stream9 image or cross-arch builds that you may encounter:
- https://github.com/osbuild/bootc-image-builder/issues/619
- https://github.com/osbuild/bootc-image-builder/issues/641

### Operating system

all OS'

### Version

next (development version)

**Comment by cdrage** [comment]
UPDATE there's a solution now!

With Rosetta disabled and the instructions from https://github.com/osbuild/bootc-image-builder/issues/619#issuecomment-2360569582 I am now able to build.

**Comment by cdrage** [comment]
Marked this as Done as part of sprint planning as we now have the document on the README: https://github.com/containers/podman-desktop-extension-bootc?tab=readme-ov-file#known-issues

But I will leave this open in case someone else stumbles upon this issue.

**Comment by cdrage** [comment]
Closing this as it's been left open since Oct 2024 and we have multiple other issues with regards to cross-arch building (and a section on our README)
